version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_NO_ANALYTICS: true
      # Log level: debug, info, warning, error
      MEILI_LOG_LEVEL: debug
volumes:
  meilisearch-data:
